### ISSUE TITLE
This code does not compile as written  

### ISSUE THREAD

**Issue by bluefinch83** [dlaptev/VarGamma#1]
I'm using 3.6 and spyder 3.2.7 to run it, so maybe it works for other people. However, for me, several key functions did not work because the author was using a map object when the code needed something that was indexed, like a list. For example, maps are not indexed, so cdf_values[i] += cdf_values[i-1] is junk code as long as cdf_values is a map. This is a simple enough fix, just do list('map_name') to index the object.

**Comment by dlaptev** [comment]
Hi @bluefinch83 , thanks for your interest and for raising the issue!

The code still works correctly in Python 2.7. However in Python 3 the `map` function returns an iterator instead of a `list`. You are totally right about that.

I just submitted a small fix, but I do not have Python 3. If you could verify that it works for you now - that would be great, thank you.
